name: Get Weather Data

on: 
  workflow_dispatch:
    inputs:
      city-id:
        required: true
        description: Enter id of a U.S city (found on openweathermap.org)

jobs:
  weather-action:
    name: Get Weather Data
    runs-on: ubuntu-latest

    steps:
      - name: Get Weather using OpenWeather 
        uses: bumb7ebee/weather-profile-actions@1.0.0
        with:
          # OpenWeather API key
          weather-api-key: ${{ secrets.OPENWEATHER_API_KEY }}
          # City ID obtained from OpenWeather
          city-id: ${{ github.event.inputs.city-id }}
          # Centigrade (c) or Fahrenheit (f)
          units: f
          # Country code obtained from https://flagicons.lipis.dev/
          country-code: um
          # README.md file path
          readme-path: ./weather_report.md
              

