name: Get Weather Data

on: 
  workflow_dispatch:
    inputs:
      city:
        required: true
        description: Enter city name or zip code

jobs:
  weather-action:
    name: Get Weather Data
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Get Weather using Weather API
      uses: huantt/weather-forecast@v1.0.6
      with:
        # City
        city: ${{ github.event.inputs.city }}
        weather-api-key: ${{ secrets.WEATHER_API_KEY }}
        # Template file path
        template-file: weather_report.md.template
        # Output file path
        out-file: weather_report.md
    - name: Commit
      run: |
          if git diff --exit-code; then
            echo "No changes to commit."
            exit 0
          else
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Updated weather report for $(date)"
            git push
          fi
