name: Get Weather Data

on: 
  workflow_dispatch:
    inputs:
      city:
        required: true
        description: Enter city name or zip code

jobs:
  weather-action:
    name: Get Weather Data
    runs-on: ubuntu-latest

    steps:
    - name: Get Weather using Weather API
      uses: huantt/weather-forecast@v1.0.6
      with:
        # City
        city: ${{ github.event.inputs.city-id }}
        weather-api-key: ${{ secrets.WEATHER_API_KEY }}
        # Template file path
        template-file: weather_report.md.template
        # Output file path
        out-file: weather_report.md
