name: Build the React App

on: workflow_dispatch

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.8

    - name: Set up React
      run: |
        npm -g install create-react-app .
      working-directory: ./simple_flask_app/frontend

    - name: Install Dependencies
      run: | 
        npm install
      working-directory: ./simple_flask_app/frontend
      
    - name: Build the app
      run: |
        npm run build
      working-directory: ./simple_flask_app/frontend
      env:
        PUBLIC_URL: ./simple_flask_app/frontend/public

    - name: Move Build
      run: |
        mv ./simple_flask_app/frontend/build ./simple_flask_app/backend/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build-files
        path: ./simple_flask_app/backend
