name: Build the React App

on: workflow_dispatch

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.8

    - name: Set up React
      run: |
        npm -g install create-react-app .
      working-directory: ./frontend

    - name: Install Dependencies
      run: | 
        npm install
      working-directory: ./frontend
      
    - name: Build the app
      run: |
        npm run build
      working-directory: ./frontend
      env:
        PUBLIC_URL: ./frontend/public

    - name: Move Build
      run: |
        mv ./frontend/build ./backend/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build-files
        path: ./backend

  run-job:
    needs: build
    name: Run App
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: app-build-files
        path: ./backend

    - name: Set up Python
      uses: actions/setup-python@v5
      with: 
        python-version: 3.8
  
    - name: Start Flask App
      run: |
        timeout 10s ./backend/simple_program.py


