name: External Event Workflow

on:
    repository_dispatch: 
        types: [testing]

jobs:
    respond:
        name: Respond
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Confirmation message
          if: ${{ !github.event.client_payload.status }}
          env:
            MESSAGE: ${{ github.event.client_payload.message }}
          run: |
            echo $MESSAGE
            echo "I think you are right!"

            